### ISSUE TITLE
Missing Object name list and corresponding scene

### ISSUE THREAD

**Issue by GuanlinWU123** [jnnan/trumans_utils#13]
Hi! Thanks for your great work! 
It seems like in the obj_list, there only include all types of chair name without other type of objects. I'm wondering where is the object name list corresponding to the 32 object value in obj_flag?
Thanks!

**Comment by jnnan** [comment]
object_flag.npy only includes chairs with original and augmented shapes, while other types of object can be found in folder Object_all. The names of 35 objects in object_flag.npy are in object_list.npy, and their rotation matrices are in object_mat.npy

**Comment by GuanlinWU123** [comment]
> object_flag.npy only includes chairs with original and augmented shapes, while other types of object can be found in folder Object_all. The names of 35 objects in object_flag.npy are in object_list.npy, and their rotation matrices are in object_mat.npy

Thanks for your reply. Now I understand the workflow of object_list and object_flag. Congratulations on your amazing work again!
