### ISSUE TITLE
Questions related to Visualization

### ISSUE THREAD

**Issue by GuanlinWU123** [jnnan/trumans_utils#15]
Thanks for your amazing work!
I'm wondering for these smplx parameters you proposed, is there a way for visualization rather than using flask? For example if there is some visualization method that can input these smplx parameters, object parameters and render the video out in .mp4 format.
Also, if we want to augment videos and generate new ones by ourselves, is there an interface or some functions provided?
Thanks!

**Comment by jnnan** [comment]
To visualize and render human motion, I utilized Blender along with the [SMPL-X addon](https://smpl-x.is.tue.mpg.de/download.php) (need to login). With this setup, users have the ability to import SMPL-X parameters to visualize human motion. Additionally, users can import scene meshes into the Blender environment.
