### ISSUE TITLE
Clarification needed on getitem function behavior in TrumansDataset class

### ISSUE THREAD

**Issue by cyp336** [jnnan/trumans_utils#16]
Hi, thank you for sharing your impressive work! I noticed that in the getitem function of the TrumansDataset class, the index idx is replaced by self.motion_ind[idx]. Could you clarify if this change makes idx a relatively small value, potentially leading to only retrieving the initial slices of the dataset?

**Comment by jnnan** [comment]
self.motion_ind is loaded from the file idx_start.npy, which contains a list of frame indices. Each frame index in this list represents a potential starting point for a consecutive sequence of 16 frames. These 16-frame sequences are considered as motion segments and are used in the auto-regressive generation process.

**Comment by cyp336** [comment]
I got it. Thank you!
