### ISSUE TITLE
Segmentation labels

### ISSUE THREAD

**Issue by MatteoGioia** [jnnan/trumans_utils#20]
Hi @jnnan, according to the project page the repository/data should include 
labels for semantic segmentation. Are you planning to release them in the near future?

Alternatively, it would be great to have the original RGB textures in order to 
run some 3rd party segmentation models.

Thanks :)

**Comment by jnnan** [comment]
The textured scenes and objects are now available. Please refer to the readme file for details. The semantic segmentation can be directly rendered using blender.
