### ISSUE TITLE
unmatched object_all

### ISSUE THREAD

**Issue by ZenGengChin** [jnnan/trumans_utils#28]
Dear Authors, 

Thanks for your excellent work. By visualizing your released data, I found that there are some unmatched objects in your motion sequences, for example. 2023-02-09@14-28-09, in this segmentation, I found that the motion of cabinet 02 (both base and door) is not correctly placed in the scene for both translation and rotation. I double-checked that the other objects were correct, but the cabinet was not. Hope this issue could gain your attention.
![Screenshot from 2024-11-12 22-34-28](https://github.com/user-attachments/assets/d632021d-b09f-4fa4-ad72-792cd840b7e0)

**Comment by albertcity** [comment]
@ZenGengChin I am also interested in TRUMANS, too. Could you please tell me how to visualisze the scenes like this? I am totally new to blender and can not find any scripts to do so.  Also, I find the authors can rendering the video with wonderful textures. Is this possible in your scenario?

Thanks for any reply :)

![截屏2024-11-13 20 24 12](https://github.com/user-attachments/assets/5f6a006d-9b91-496a-b54d-c3d6336ae315)

**Comment by ZenGengChin** [comment]
I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects. 

In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.

**Comment by albertcity** [comment]
> I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects.
> 
> In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.

Thanks a lot! Here is my email address: yiqi@mail.ustc.edu.cn. Really looking forward to your contact :)

**Comment by ZenGengChin** [comment]
> > I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects.
> > In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.
> 
> Thanks a lot! Here is my email address: [yiqi@mail.ustc.edu.cn](mailto:yiqi@mail.ustc.edu.cn). Really looking forward to your contact :)

email was sent, hope to hear from you.

**Comment by jnnan** [comment]
We are reviewing the motion capture data files for accuracy as much as we can. The textured scenes and objects have been released - please check the readme file for more information.

**Comment by ZenGengChin** [comment]
Thanks for your message, looking forward to your new works in the coming months.

**Comment by ZenGengChin** [comment]
closed

**Comment by jyf588** [comment]
I can verify on this same sequence 2023-02-09@14-28-09, this cabinet misplacement is still an issue on the latest version of data. And similar problems persist on some other sequences as well. Any updates on fixes?

I am also wondering why the rendered videos do not seem to have similar problems. Since OP and I seem to use very different tools to visualize the motion but see exactly the same issues, it's not very likely that we both had a same bug independently in our codebases.

**Comment by Pcc123456** [comment]
> I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects.
> 
> In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.

Hello, I am also very interested in this implementation method. Could you please assist me? Thank you very much. My email address is pccshuai@gmail.com.

**Comment by Pcc123456** [comment]
> > I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects.
> > In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.
> 
> Thanks a lot! Here is my email address: [yiqi@mail.ustc.edu.cn](mailto:yiqi@mail.ustc.edu.cn). Really looking forward to your contact :)

Hello, I am also very interested in this implementation method. Could you please assist me? Thank you very much. My email address is pccshuai@gmail.com.

**Comment by jiewjwang** [comment]
> I am also interested in the authors' visualization, apparently, you can skin the SMPL armature with any meshes or textures. And according to the author's visualization using flask, they may have their beautified models of the scenes and objects.
> 
> In my implementation, I use the SMPLX by MPI for blender and load the obj files by blender script with motion keyframing. If you are interested in the implementation, you can leave your contact information by replying this comment and I am more than happy to help.

@ZenGengChin  Hi, I'm also interested in the solution you mentioned. Could you send me a copy? My email address is 774855856wj@gmail.com. I look forward to your reply.
