### ISSUE TITLE
Can't run the demo.

### ISSUE THREAD

**Issue by Colmar-zlicheng** [jnnan/trumans_utils#3]
Hi, I run the command below, but the interface does not include any scene.

```
python3 -m flask run --host=0.0.0.0
```

<img width="1505" alt="截屏2024-06-17 01 08 22" src="https://github.com/jnnan/trumans_utils/assets/111580763/1d63f761-a700-4bee-b286-77470a7b1b28">

**Comment by jnnan** [comment]
This bug has been fixed. Please download the latest version.

**Comment by Colmar-zlicheng** [comment]
Thank you!
