### ISSUE TITLE
Inquiry about hand parameters for SMPL-X

### ISSUE THREAD

**Issue by xiaogangpeng** [jnnan/trumans_utils#6]
Dear authors,

Thanks for this interesting work. I'd like to ask when your team will release the hand pose parameters for the SMPL-X data. Looking forward to your reply.

Best,
Xiaogang

**Comment by jnnan** [comment]
Hand pose parameters in SMPL-X have been uploaded. Please download from the original google drive link.

**Comment by xiaogangpeng** [comment]
> Hand pose parameters in SMPL-X have been uploaded. Please download from the original google drive link.

Thank you! I found it after refreshing the previous Google Drive link.
